### ISSUE TITLE
Custom timeout doesn't work to assist.notify

### ISSUE THREAD

**Issue by morelazers** [blocknative/assist#194] opened 2019-05-22 03:02 UTC
Always dismisses after 5 seconds.

**Comment by liamaharon** [comment] 2019-05-22 03:10
I'm unable to reproduce this. Can you link a repo with the issue?

**Comment by morelazers** [comment] 2019-05-22 05:03
https://github.com/MostlyUnemployed/C.R.E.A.M

Apologies for shitty code.

`yarn && yarn start` should work, set your metamask to mainnet, start a tx and then watch the notification disappear.

Code is in `utils/wallet/index.js`

**Comment by liamaharon** [comment] 2019-05-22 06:00
Resolved with @morelazers offline, the project was using a pre-release version of the notify API

**Closed by liamaharon** 2019-05-22 06:00 UTC
Labels: bug
